use crate::{
    ec::{EllipticCurve, Point},
    finite_fields::FiniteField,
};
use num_bigint::{BigUint, RandBigInt};
use rand::thread_rng;
use sha256::digest;

/// An ECDSA context tied to a specific elliptic curve and generator point.
///
/// Holds the public domain parameters needed for key generation, signing, and
/// verification.  All operations are performed over the subgroup generated by
/// `generator`, whose order is `order`.
pub struct ECDSA {
    pub elliptic_curve: EllipticCurve,
    /// Generator point `G` — the base point of the subgroup.
    pub generator: Point,
    /// The order `n` of the subgroup generated by `generator`.
    pub order: BigUint,
}

impl ECDSA {
    /// Generates a random (private key, public key) pair.
    ///
    /// Returns `(d, B)` where `d` is a random scalar in `[1, order)` and
    /// `B = d · G` is the corresponding public key.
    pub fn generate_key_pair(&self) -> (BigUint, Point) {
        let private_key = self.generate_private_key();
        let public_key = self.generate_public_key(&private_key);

        (private_key, public_key)
    }

    /// Generates a random private key scalar in `[1, order)`.
    pub fn generate_private_key(&self) -> BigUint {
        self.random_scalar()
    }

    /// Derives the public key `d · G` from a private key scalar `d`.
    pub fn generate_public_key(&self, private_key: &BigUint) -> Point {
        self.elliptic_curve.scalar_mul(&self.generator, private_key)
    }

    /// Hashes a message string with SHA-256 and returns the result as a `BigUint`
    /// reduced modulo the group order, making it safe to pass directly to [`sign`].
    ///
    /// The reduction `hash mod order` is a simplification: the standard (RFC 6979)
    /// truncates the hash to the bit-length of the order instead.  For 256-bit
    /// curves and SHA-256 the difference is negligible for educational purposes.
    ///
    /// [`sign`]: ECDSA::sign
    pub fn hash_message(&self, message: &str) -> BigUint {
        let hex_str = digest(message);
        let bytes = hex::decode(&hex_str).expect("sha256 output is always valid hex");
        BigUint::from_bytes_be(&bytes) % &self.order
    }

    /// Generates a random scalar in the half-open range `[1, max)`.
    pub fn random_scalar(&self) -> BigUint {
        let mut rng = thread_rng();
        rng.gen_biguint_range(&BigUint::from(1u32), &self.order)
    }

    /// Signs a message hash and returns the signature `(r, s)`.
    ///
    /// The caller is responsible for hashing the message before passing it in.
    /// `k_random` is the ephemeral nonce; **it must be kept secret and must
    /// never be reused** — reuse leaks the private key.
    ///
    /// The signing equation is:
    /// ```text
    /// R = k · G,  r = R.x mod order
    /// s = (hash + d · r) · k⁻¹  mod order
    /// ```
    ///
    /// # Panics
    /// Panics if any of the inputs are ≥ `order`, or if `k · G` is the identity.
    pub fn sign(
        &self,
        hash: &BigUint,
        private_key: &BigUint,
        k_random: &BigUint,
    ) -> (BigUint, BigUint) {
        assert!(*hash < self.order, "Hash is bigger than the order");
        assert!(
            *private_key < self.order,
            "Private key is bigger than the order"
        );
        assert!(
            *k_random < self.order,
            "Random number k is bigger than the order"
        );

        let Point::Coordonate { x: r, y: _ } =
            self.elliptic_curve.scalar_mul(&self.generator, k_random)
        else {
            panic!("The random point R should not be the identity");
        };

        let k_inv = FiniteField::inverse_mul_prime(k_random, &self.order);
        let s = FiniteField::add(
            hash,
            &FiniteField::mul(&r, private_key, &self.order),
            &self.order,
        );
        let s = FiniteField::mul(&s, &k_inv, &self.order);

        (r, s)
    }

    /// Verifies a signature `(r, s)` against a message hash and a public key.
    ///
    /// The verification equation is:
    /// ```text
    /// u1 = s⁻¹ · hash  mod order
    /// u2 = s⁻¹ · r     mod order
    /// P  = u1 · G + u2 · B
    /// valid ⟺ P.x == r
    /// ```
    ///
    /// Returns `false` for any structurally invalid signature (including one
    /// that causes the computed point `P` to be the identity).
    pub fn verify(
        &self,
        hash: &BigUint,
        public_key: &Point,
        signature: &(BigUint, BigUint),
    ) -> bool {
        let s_inv = FiniteField::inverse_mul_prime(&signature.1, &self.order);
        let u1 = FiniteField::mul(&s_inv, hash, &self.order);
        let u2 = FiniteField::mul(&s_inv, &signature.0, &self.order);

        let p = self.elliptic_curve.add(
            &self.elliptic_curve.scalar_mul(&self.generator, &u1),
            &self.elliptic_curve.scalar_mul(public_key, &u2),
        );

        match p {
            Point::Coordonate { x: xp, y: _ } => xp == signature.0,
            Point::Identity => false,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ec::{EllipticCurve, Point};

    // y^2 = x^3 + 2x + 2 mod 17, G = (5, 1), order = 19
    fn small_curve_ecdsa() -> ECDSA {
        ECDSA {
            elliptic_curve: EllipticCurve {
                a: BigUint::from(2u32),
                b: BigUint::from(2u32),
                p: BigUint::from(17u32),
            },
            generator: Point::Coordonate {
                x: BigUint::from(5u32),
                y: BigUint::from(1u32),
            },
            order: BigUint::from(19u32),
        }
    }

    #[test]
    fn test_private_key_in_range() {
        let ecdsa = small_curve_ecdsa();
        let private_key = ecdsa.generate_private_key();
        assert!(private_key >= BigUint::from(1u32));
        assert!(private_key < ecdsa.order);
    }

    #[test]
    fn test_public_key_is_on_curve() {
        let ecdsa = small_curve_ecdsa();
        let (_, public_key) = ecdsa.generate_key_pair();
        assert!(ecdsa.elliptic_curve.is_on_curve(&public_key));
        assert_ne!(public_key, Point::Identity);
    }

    #[test]
    fn test_public_key_equals_private_key_times_generator() {
        let ecdsa = small_curve_ecdsa();
        let (private_key, public_key) = ecdsa.generate_key_pair();
        let expected = ecdsa.elliptic_curve.scalar_mul(&ecdsa.generator, &private_key);
        assert_eq!(public_key, expected);
    }

    // With k=2: 2*G = (6, 3), r=6
    // k_inv = 2^-1 mod 19 = 10
    // s = (1 + 7*6) * 10 mod 19 = 43*10 mod 19 = 5*10 mod 19 = 12
    #[test]
    fn test_sign_known_values() {
        let ecdsa = small_curve_ecdsa();
        let hash = BigUint::from(1u32);
        let private_key = BigUint::from(7u32);
        let k = BigUint::from(2u32);

        let (r, s) = ecdsa.sign(&hash, &private_key, &k);

        assert_eq!(r, BigUint::from(6u32));
        assert_eq!(s, BigUint::from(12u32));
    }

    #[test]
    fn test_sign_outputs_in_range() {
        let ecdsa = small_curve_ecdsa();
        let hash = BigUint::from(5u32);
        let private_key = BigUint::from(3u32);
        let k = BigUint::from(4u32);

        let (r, s) = ecdsa.sign(&hash, &private_key, &k);

        assert!(r >= BigUint::from(1u32));
        assert!(r < ecdsa.order);
        assert!(s >= BigUint::from(1u32));
        assert!(s < ecdsa.order);
    }

    #[test]
    #[should_panic(expected = "Hash is bigger than the order")]
    fn test_sign_panics_if_hash_too_large() {
        let ecdsa = small_curve_ecdsa();
        ecdsa.sign(
            &ecdsa.order.clone(),
            &BigUint::from(1u32),
            &BigUint::from(1u32),
        );
    }

    #[test]
    #[should_panic(expected = "Private key is bigger than the order")]
    fn test_sign_panics_if_private_key_too_large() {
        let ecdsa = small_curve_ecdsa();
        ecdsa.sign(
            &BigUint::from(1u32),
            &ecdsa.order.clone(),
            &BigUint::from(1u32),
        );
    }

    #[test]
    #[should_panic(expected = "Random number k is bigger than the order")]
    fn test_sign_panics_if_k_too_large() {
        let ecdsa = small_curve_ecdsa();
        ecdsa.sign(
            &BigUint::from(1u32),
            &BigUint::from(1u32),
            &ecdsa.order.clone(),
        );
    }

    // hash=1, private_key=7, k=2 -> (r=6, s=12), public_key = 7*G = (0, 6)
    fn known_signature() -> (BigUint, Point, (BigUint, BigUint)) {
        let hash = BigUint::from(1u32);
        let public_key = Point::Coordonate {
            x: BigUint::from(0u32),
            y: BigUint::from(6u32),
        };
        let signature = (BigUint::from(6u32), BigUint::from(12u32));
        (hash, public_key, signature)
    }

    #[test]
    fn test_verify_valid_signature() {
        let ecdsa = small_curve_ecdsa();
        let (hash, public_key, signature) = known_signature();
        assert!(ecdsa.verify(&hash, &public_key, &signature));
    }

    #[test]
    fn test_verify_wrong_hash() {
        let ecdsa = small_curve_ecdsa();
        let (_, public_key, signature) = known_signature();
        let wrong_hash = BigUint::from(2u32);
        assert!(!ecdsa.verify(&wrong_hash, &public_key, &signature));
    }

    #[test]
    fn test_verify_wrong_r() {
        let ecdsa = small_curve_ecdsa();
        let (hash, public_key, (_, s)) = known_signature();
        let bad_sig = (BigUint::from(7u32), s);
        assert!(!ecdsa.verify(&hash, &public_key, &bad_sig));
    }

    #[test]
    fn test_verify_wrong_s() {
        let ecdsa = small_curve_ecdsa();
        let (hash, public_key, (r, _)) = known_signature();
        let bad_sig = (r, BigUint::from(5u32));
        assert!(!ecdsa.verify(&hash, &public_key, &bad_sig));
    }

    #[test]
    fn test_verify_wrong_public_key() {
        let ecdsa = small_curve_ecdsa();
        let (hash, _, signature) = known_signature();
        // 2*G = (6, 3) — a different valid point, not the signer's key
        let wrong_key = Point::Coordonate {
            x: BigUint::from(6u32),
            y: BigUint::from(3u32),
        };
        assert!(!ecdsa.verify(&hash, &wrong_key, &signature));
    }

    #[test]
    fn test_verify_sign_roundtrip() {
        let ecdsa = small_curve_ecdsa();
        let hash = BigUint::from(3u32);
        let private_key = BigUint::from(5u32);
        let k = BigUint::from(4u32);
        let public_key = ecdsa.generate_public_key(&private_key);
        let signature = ecdsa.sign(&hash, &private_key, &k);
        assert!(ecdsa.verify(&hash, &public_key, &signature));
    }

    #[test]
    fn test_hash_message_is_in_range() {
        let ecdsa = small_curve_ecdsa();
        let hash = ecdsa.hash_message("hello world");
        assert!(hash < ecdsa.order);
    }

    #[test]
    fn test_hash_message_is_deterministic() {
        let ecdsa = small_curve_ecdsa();
        assert_eq!(ecdsa.hash_message("hello"), ecdsa.hash_message("hello"));
    }

    #[test]
    fn test_hash_message_different_inputs_differ() {
        let ecdsa = small_curve_ecdsa();
        assert_ne!(ecdsa.hash_message("hello"), ecdsa.hash_message("world"));
    }

    #[test]
    fn test_hash_sign_verify_roundtrip() {
        let ecdsa = small_curve_ecdsa();
        let (private_key, public_key) = ecdsa.generate_key_pair();
        let hash = ecdsa.hash_message("hello world");
        let k = ecdsa.random_scalar();
        let signature = ecdsa.sign(&hash, &private_key, &k);
        assert!(ecdsa.verify(&hash, &public_key, &signature));
    }

    #[test]
    fn test_verify_roundtrip_random_keys() {
        let ecdsa = small_curve_ecdsa();
        let hash = BigUint::from(7u32);
        let (private_key, public_key) = ecdsa.generate_key_pair();
        let k = ecdsa.random_scalar();
        let signature = ecdsa.sign(&hash, &private_key, &k);
        assert!(ecdsa.verify(&hash, &public_key, &signature));
    }
}
